<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>BnW - Говнодоки</title>
    <link rel="stylesheet" href="http://bnw.blasux.ru/static/basestyle.css" type="text/css" />
    <style type="text/css">
        .redlink {
            background-color: #CD0000;
            color: #E5E5E5;
            text-decoration: none;
        }
        
        #err_outer {width: 100%; overflow: hidden; position: relative;}
        #err_outer[id] {display: table; position: static;}
        #err_middle {position: absolute; top: 50%;} /* for explorer only*/
        #err_middle[id] {display: table-cell; vertical-align: middle; width: 100%;}
        #err_inner { background-color: #CD0000; padding: 1em; width: 40em; margin-left: auto; margin-right: auto; position: relative; top: -50%} /* for explorer only */        
        #err_inner2 { padding: 1em; border: thin solid white; text-align: center; }
    </style>
</head>
<body>
<div class='bodyshit'>
    <div style='text-align: right; overflow: hidden; width: 100%;'>
        <a href='/' style='color: #e5e5e5; text-decoration: none;'>Вот.</a>
    </div>
    <div class='outerborder'>
        <div class='msg'>
            <p style='text-align: center;'>
                <a class="redlink" href="/static/">&nbsp;О проекте&nbsp;</a>
                <a class="redlink" href="/static/interfaces.html">&nbsp;Описание интерфейсов&nbsp;</a>
                <a class="redlink" href="/static/contacts.html">&nbsp;Контакты&nbsp;</a>
                <a class="redlink" href="http://www.ohloh.net/p/blackjackandwhores">&nbsp;Страничка на ohloh&nbsp;</a>
                <a class="redlink" href="/static/appeal.html">&nbsp;Обращение&nbsp;</a>
            </p>