all: index.html contacts.html interfaces.html
index.html: head.inc index.tmpl foot.inc
	cat head.inc index.tmpl foot.inc > index.html

contacts.html: head.inc contacts.tmpl foot.inc
	cat head.inc contacts.tmpl foot.inc > contacts.html

interfaces.html: head.inc interfaces.tmpl foot.inc
	cat head.inc interfaces.tmpl foot.inc > interfaces.html
